"""SQLite telemetry store for SSHintel.

Provides a queryable, persistent store for the structured security events
generated by the honeypot. JSONL remains the raw source of truth; this module
is an additional persistence and analysis layer.

Thread safety: a single shared connection is protected by a threading.Lock,
so concurrent SSH sessions can safely record telemetry. WAL mode is enabled
for better concurrent read performance.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1

DEFAULT_DB_PATH = Path(__file__).parent.parent / "data" / "sshintel.db"

CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS events (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    session_id      TEXT,
    source_ip       TEXT,
    source_port     INTEGER,
    username        TEXT,
    command         TEXT,
    cwd             TEXT,
    metadata        TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id      TEXT PRIMARY KEY,
    source_ip       TEXT,
    username        TEXT,
    started_at      TEXT,
    ended_at        TEXT,
    duration        REAL,
    status          TEXT,
    disconnect_reason TEXT
);

CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT
);
"""

INDEXES_SQL = [
    "CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);",
    "CREATE INDEX IF NOT EXISTS idx_events_event_type ON events(event_type);",
    "CREATE INDEX IF NOT EXISTS idx_events_session_id ON events(session_id);",
    "CREATE INDEX IF NOT EXISTS idx_events_source_ip ON events(source_ip);",
    "CREATE INDEX IF NOT EXISTS idx_events_username ON events(username);",
    "CREATE INDEX IF NOT EXISTS idx_sessions_source_ip ON sessions(source_ip);",
    "CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON sessions(started_at);",
]


class TelemetryStore:
    """Persistent SQLite store for SSH security events."""

    def __init__(self, db_path=None):
        if db_path is None:
            db_path = DEFAULT_DB_PATH
        self.db_path = Path(db_path)
        self._lock = threading.Lock()
        self._conn = None

    def open(self):
        if self._conn is not None:
            return
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(
            str(self.db_path), check_same_thread=False, timeout=10
        )
        self._conn.execute("PRAGMA journal_mode=WAL;")
        self._create_schema()

    def close(self):
        if self._conn is not None:
            try:
                self._conn.close()
            except Exception:
                pass
            self._conn = None

    @property
    def is_open(self):
        return self._conn is not None

    def _create_schema(self):
        assert self._conn is not None
        with self._lock:
            self._conn.executescript(CREATE_TABLES_SQL)
            for stmt in INDEXES_SQL:
                self._conn.execute(stmt)
            self._conn.execute(
                "INSERT OR REPLACE INTO meta(key, value) VALUES('schema_version', ?)",
                (str(SCHEMA_VERSION),),
            )
            self._conn.commit()

    def log_event(self, event):
        if self._conn is None:
            return
        known_keys = {
            "timestamp", "event_type", "session_id", "source_ip",
            "source_port", "username", "command", "cwd",
        }
        try:
            metadata = {k: v for k, v in event.items() if k not in known_keys}
            with self._lock:
                self._conn.execute(
                    "INSERT INTO events (timestamp, event_type, session_id, "
                    "source_ip, source_port, username, command, cwd, metadata) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        event.get("timestamp"),
                        event.get("event_type"),
                        event.get("session_id"),
                        event.get("source_ip"),
                        event.get("source_port"),
                        event.get("username"),
                        event.get("command"),
                        event.get("cwd"),
                        json.dumps(metadata, ensure_ascii=False) if metadata else None,
                    ),
                )
                self._conn.commit()
        except Exception as exc:
            print(f"!!! SQLite telemetry error: {exc}")

    def record_session_connect(self, session_id, source_ip, connected_at):
        if self._conn is None:
            return
        try:
            with self._lock:
                self._conn.execute(
                    "INSERT OR IGNORE INTO sessions "
                    "(session_id, source_ip, started_at) VALUES (?, ?, ?)",
                    (session_id, source_ip, connected_at),
                )
                self._conn.commit()
        except Exception as exc:
            print(f"!!! SQLite session-connect error: {exc}")

    def record_session_finalize(self, session_id, username, ended_at,
                                duration, status, disconnect_reason):
        if self._conn is None:
            return
        try:
            with self._lock:
                self._conn.execute(
                    "INSERT OR REPLACE INTO sessions "
                    "(session_id, source_ip, username, started_at, ended_at, "
                    "duration, status, disconnect_reason) "
                    "VALUES(?, "
                    "COALESCE((SELECT source_ip FROM sessions "
                    "WHERE session_id=?), ''), ?, "
                    "COALESCE((SELECT started_at FROM sessions "
                    "WHERE session_id=?), ''), "
                    "?, ?, ?, ?)",
                    (session_id, session_id, username, session_id,
                     ended_at, duration, status, disconnect_reason),
                )
                self._conn.commit()
        except Exception as exc:
            print(f"!!! SQLite session-finalize error: {exc}")

    # ---- Query helpers ----

    def count_sessions(self):
        return self._query_scalar("SELECT COUNT(*) FROM sessions")

    def count_events(self):
        return self._query_scalar("SELECT COUNT(*) FROM events")

    def unique_ips(self):
        return self._query_scalar(
            "SELECT COUNT(DISTINCT source_ip) FROM events"
        )

    def total_auth_attempts(self):
        return self._query_scalar(
            "SELECT COUNT(*) FROM events WHERE event_type='auth_attempt'"
        )

    def failed_auth_attempts(self):
        return self._query_scalar(
            "SELECT COUNT(*) FROM events WHERE event_type='auth_failure'"
        )

    def successful_auths(self):
        return self._query_scalar(
            "SELECT COUNT(*) FROM events WHERE event_type='auth_success'"
        )

    def total_commands(self):
        return self._query_scalar(
            "SELECT COUNT(*) FROM events WHERE event_type='command'"
        )

    def top_usernames(self, limit=10):
        rows = self._query_all(
            "SELECT username, COUNT(*) as c FROM events "
            "WHERE username IS NOT NULL "
            "GROUP BY username ORDER BY c DESC LIMIT ?",
            (limit,),
        )
        return [{"username": r[0], "count": r[1]} for r in rows]

    def top_commands(self, limit=10):
        rows = self._query_all(
            "SELECT command, COUNT(*) as c FROM events "
            "WHERE event_type='command' AND command IS NOT NULL "
            "GROUP BY command ORDER BY c DESC LIMIT ?",
            (limit,),
        )
        return [{"command": r[0], "count": r[1]} for r in rows]

    def top_source_ips(self, limit=10):
        rows = self._query_all(
            "SELECT source_ip, COUNT(*) as c FROM events "
            "WHERE source_ip IS NOT NULL "
            "GROUP BY source_ip ORDER BY c DESC LIMIT ?",
            (limit,),
        )
        return [{"source_ip": r[0], "count": r[1]} for r in rows]

    def get_session_events(self, session_id):
        rows = self._query_all(
            "SELECT timestamp, event_type, session_id, source_ip, "
            "source_port, username, command, cwd, metadata "
            "FROM events WHERE session_id=? ORDER BY id ASC",
            (session_id,),
        )
        return [self._row_to_dict(r) for r in rows]

    def get_events_by_ip(self, ip, limit=50):
        rows = self._query_all(
            "SELECT timestamp, event_type, session_id, source_ip, "
            "source_port, username, command, cwd, metadata "
            "FROM events WHERE source_ip=? ORDER BY id DESC LIMIT ?",
            (ip, limit),
        )
        return [self._row_to_dict(r) for r in rows]

    def get_recent_events(self, limit=50):
        rows = self._query_all(
            "SELECT timestamp, event_type, session_id, source_ip, "
            "source_port, username, command, cwd, metadata "
            "FROM events ORDER BY id DESC LIMIT ?",
            (limit,),
        )
        return [self._row_to_dict(r) for r in rows]

    def get_recent_sessions(self, limit=20):
        rows = self._query_all(
            "SELECT session_id, source_ip, username, started_at, ended_at, "
            "duration, status, disconnect_reason "
            "FROM sessions ORDER BY started_at DESC LIMIT ?",
            (limit,),
        )
        cols = ["session_id", "source_ip", "username", "started_at",
                "ended_at", "duration", "status", "disconnect_reason"]
        return [dict(zip(cols, r)) for r in rows]

    def events_in_range(self, start, end, limit=100):
        rows = self._query_all(
            "SELECT timestamp, event_type, session_id, source_ip, "
            "source_port, username, command, cwd, metadata "
            "FROM events WHERE timestamp>=? AND timestamp<=? "
            "ORDER BY id ASC LIMIT ?",
            (start, end, limit),
        )
        return [self._row_to_dict(r) for r in rows]

    def sessions_in_range(self, start, end, limit=100):
        rows = self._query_all(
            "SELECT session_id, source_ip, username, started_at, ended_at, "
            "duration, status, disconnect_reason "
            "FROM sessions WHERE started_at>=? AND started_at<=? "
            "ORDER BY started_at ASC LIMIT ?",
            (start, end, limit),
        )
        cols = ["session_id", "source_ip", "username", "started_at",
                "ended_at", "duration", "status", "disconnect_reason"]
        return [dict(zip(cols, r)) for r in rows]

    def activity_by_hour(self, hours=24):
        """Return event counts grouped by hour for the activity chart.

        Returns a list of {"hour": "YYYY-MM-DD HH:00", "count": N} dicts,
        oldest first, covering the last ``hours`` hours.
        """
        rows = self._query_all(
            "SELECT strftime('%Y-%m-%d %H:00', timestamp) AS hour, "
            "COUNT(*) AS cnt "
            "FROM events "
            "WHERE timestamp >= datetime('now', ?) "
            "GROUP BY hour ORDER BY hour ASC",
            (f"-{hours} hours",),
        )
        return [{"hour": r[0], "count": r[1]} for r in rows]

    # ---- Internal helpers ----

    def _query_scalar(self, sql, params=()):
        if self._conn is None:
            return 0
        try:
            with self._lock:
                cur = self._conn.execute(sql, params)
                row = cur.fetchone()
                return row[0] if row else 0
        except Exception as exc:
            print(f"!!! SQLite query error: {exc}")
            return 0

    def _query_all(self, sql, params=()):
        if self._conn is None:
            return []
        try:
            with self._lock:
                cur = self._conn.execute(sql, params)
                return cur.fetchall()
        except Exception as exc:
            print(f"!!! SQLite query error: {exc}")
            return []

    @staticmethod
    def _row_to_dict(row):
        keys = ["timestamp", "event_type", "session_id", "source_ip",
                "source_port", "username", "command", "cwd", "metadata"]
        d = dict(zip(keys, row))
        if d.get("metadata"):
            try:
                d["metadata"] = json.loads(d["metadata"])
            except Exception:
                pass
        else:
            d.pop("metadata", None)
        return d
